### PR TITLE
INF-2144 - Changes to run as pipeline in Jenkins

### PR DESCRIPTION
**Pull request by DMaxfield-BDS**
* Change to make a main project with 2 sub-projects
* Use version from gradle.properties
* Remove settings.gradle from sub-projects
* Move gradlew and gradle to top level directory
* Move common items to top level build.gradle

### CODE REVIEW

**Comment by romeara** [comment]
There is a file in the root, .travis.yml, that controls the gradle build. You'll want to adjust it to do gradle things from root now, so those checks above pass

**Comment by DMaxfield-BDS** [comment]
@romeara  Ya, didn't think of Travis until I saw it fail. I will look into that now

**Comment by romeara** [comment]
Overall in terms of Gradle, I think this a decent and servicable step 1 in setting them up as sub-projects, aside from the Travis fixin work

**Comment by romeara** [comment]
@DMaxfield-BDS Ah, did you add that "apply from" line for the BDS artifactory thingy? We don't use internal artifactory stuff in OSS projects like this, as people outside won't be able to build

**Pull request merged**
